# Generated by Django 4.2.2 on 2023-11-07 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_telegramchannel"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramchannel",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
